version: "3"

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "8001:8001"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./frontend:/app
  #   networks:
  #     - ft_transcendence
  #   depends_on:
  #     - backend

  backend:
    image: backend
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - ft_transcendence
    depends_on:
      - database

  database:
    image: postgres
    container_name: database
    env_file:
      - .env
    networks:
      - ft_transcendence
    volumes:
      -  postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge