version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    networks:
      - ft_transcendence
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - ft_transcendence
    depends_on:
      - database

  database:
    image: postgres
    env_file:
      - .env
    networks:
      - ft_transcendence
    volumes:
      -  postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  ft_transcendence:
    driver: bridge